#
## Base Node
FROM node:carbon

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

WORKDIR /usr/app/unthicc

COPY package.json yarn.lock ./

RUN yarn

COPY backpack.config.js babel.config.js ./
COPY services/keys ./services/keys

CMD ["yarn", "keys:dev"]
