version: '3.6'

services:
  keys:
    build:
      context: ./
      dockerfile: services/keys/Dockerfile
    environment:
      - PORT=3123
      - HOST=0.0.0.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    networks:
      - webnet

networks:
  webnet:
