version: '3.6'

services:
  traefik:
    command: --api --docker --docker.watch
    ports:
      - "80:80"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    networks:
      - traefik-net
  
  keys:
    image: keys:dev
    labels:
      - "traefik.enable=true"
      - "traefik.port=3123"
      - "traefik.backend=keys"
      - "traefik.frontend.rule=PathPrefix:/api/keys"
      - "traefik.docker.network=traefik-net"
    build:
      context: ../../../go/src/keys
      dockerfile: Dockerfile
      target: deps
    command: modd
    volumes:
      - '../../../go/src/keys:/go/src/keys'
    networks:
      - traefik-net
      - unthicc-net

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - unthicc-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - unthicc-net

networks:
  unthicc-net:
    name: unthicc-net
  traefik-net:
    name: traefik-net
