version: '3.6'

services:
  traefik:
    command: --api --docker --docker.swarmMode --docker.watch
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - /root/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - traefik-net

  keys:
    build:
      context: ./
      dockerfile: services/keys/Dockerfile
    environment:
      - PORT=3123
      - HOST=0.0.0.0
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.port=3123"
        - "traefik.backend=keys"
        - "traefik.frontend.rule=PathPrefixStrip:/api/keys"
        - "traefik.docker.network=traefik-net"
      restart_policy:
        condition: on-failure
    networks:
      - traefik-net

networks:
  traefik-net:
    name: traefik-net
    driver: overlay
