version: '3.6'

services:

  keys:
    image: registry.gitlab.com/denicho/unthicc/keys:master

  nginx:
    image: registry.gitlab.com/denicho/unthicc/nginx:master
    restart: always
    links:
      - keys
